apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: run-service
  name: run-service
  namespace: user-ns-hiteshrb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: run-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: run-service
    spec:
      containers:
      - image: public.ecr.aws/o6u7e2l7/bsidesnova2022:hiteshrb-workshop-application-c7515b647c033b558f98553c0db2aa4dd14bd25f
        imagePullPolicy: Always
        name: pause
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
